# -*- coding: utf-8 -*-
# vim: ft=yaml
---
# For help on this file's format, see https://kitchen.ci/
driver:
  name: docker
  use_sudo: false
  privileged: true
  run_command: /lib/systemd/systemd

platforms:
  ## SALT `3003.0`
  - name: ubuntu-2004-3003-0-py3
    driver:
      image: saltimages/salt-3003.0-py3:ubuntu-20.04
  - name: ubuntu-1804-3003-0-py3
    driver:
      image: saltimages/salt-3003.0-py3:ubuntu-18.04
  - name: centos-8-3003-0-py3
    driver:
      image: saltimages/salt-3003.0-py3:centos-8
  - name: centos-7-3003-0-py3
    driver:
      image: saltimages/salt-3003.0-py3:centos-7
  - name: fedora-34-3003-0-py3
    driver:
      image: saltimages/salt-3003.0-py3:fedora-34
  - name: amazonlinux-2-3003-0-py3
    driver:
      image: saltimages/salt-3003.0-py3:amazonlinux-2

  ## SALT `3000.9`
  - name: ubuntu-1804-3000-9-py3
    driver:
      image: saltimages/salt-3000.9-py3:ubuntu-18.04
  - name: centos-8-3000-9-py3
    driver:
      image: saltimages/salt-3000.9-py3:centos-8
  - name: centos-7-3000-9-py3
    driver:
      image: saltimages/salt-3000.9-py3:centos-7
  - name: opensuse-leap-152-3000-9-py3
    driver:
      image: saltimages/salt-3000.9-py3:opensuse-leap-15.2
      run_command: /usr/lib/systemd/systemd
    # Workaround to avoid intermittent failures on `opensuse-leap-15.2`:
    # => SCP did not finish successfully (255):  (Net::SCP::Error)
    transport:
      max_ssh_sessions: 1
  - name: amazonlinux-2-3000-9-py3
    driver:
      image: saltimages/salt-3000.9-py3:amazonlinux-2
  - name: ubuntu-1804-3000-9-py2
    driver:
      image: saltimages/salt-3000.9-py2:ubuntu-18.04

provisioner:
  name: salt_solo
  is_file_root: true
  log_level: debug
  salt_install: none
  require_chef: false
  state_top_from_file: true
  pillars_from_directories:
    - ../pillar
  salt_copy_filter:
    - .kitchen
    - .git

verifier:
  # https://www.inspec.io/
  name: inspec
  sudo: true
  # cli, documentation, html, progress, json, json-min, json-rspec, junit
  reporter:
    - cli

suites:
  - name: default
    include:
      - ubuntu-2004-3003-0-py3
      - ubuntu-1804-3000-9-py3
      - amazonlinux-2-3000-9-py3
      - centos-8-3000-9-py3
      - centos-7-3000-9-py3
      - opensuse-leap-152-3000-9-py3
    provisioner:
      salt_env: dev
    verifier:
      inspec_tests:
        - path: ../test/integration/default
