name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    paths:
      - "pillar/**"
      - "states/**"
      - "test/**"
jobs:
  Tests:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-2004
          - amazonlinux-2
          - centos-8-3000
          - opensuse-leap-152
    steps:
      - uses: actions/checkout@v2

      - name: Install System Deps
        run: |
          sudo apt-get update
          sudo apt-get install -y curl git

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Test
        run: |
          BRANCH=${GITHUB_REF##*\/}
          echo "|dev|qa|main|" | grep "|${BRANCH}|" || (echo "the branch: ${BRANCH} is not supported!"; exit 1)
          mkdir -p build/salt
          cp -a states/* build/salt/
          cp -a pillar build/
          cp .kitchen.yml build/salt/
          cd build/salt/
          LANG=en_US.UTF-8 bundle exec kitchen converge ${BRANCH}-${{ matrix.os }}
          LANG=en_US.UTF-8 bundle exec kitchen verify ${BRANCH}-${{ matrix.os }}

      - name: Cleanup
        if: always()
        run: |
          cd build/salt/
          bundle exec kitchen destroy
          cd ../..
          rm -rf build/
